import type { CookieDetail } from "./api";

/**
 * Cookie interchange formats, matching cookie-editor
 * (https://github.com/moustachauve/cookie-editor):
 *   - json:     array of Chrome `cookies.Cookie` objects
 *   - header:   a Cookie request header string ("a=1; b=2")
 *   - netscape: the Netscape / cURL cookies.txt tab-separated format
 * Pure functions; no browser-API deps.
 */
export type CookieFormat = "json" | "header" | "netscape";

interface EditorCookie {
  name?: string;
  value?: string;
  domain?: string; // leading dot when not hostOnly
  path?: string;
  secure?: boolean;
  httpOnly?: boolean;
  hostOnly?: boolean;
  session?: boolean;
  sameSite?: string | null; // no_restriction | lax | strict | null
  expirationDate?: number; // epoch seconds (float)
  storeId?: string | null;
}

// cookie-editor emits null (not "unspecified") for an unset sameSite.
function toEditorSameSite(s: CookieDetail["sameSite"]): string | null {
  if (s === "none") return "no_restriction";
  if (s === "lax") return "lax";
  if (s === "strict") return "strict";
  return null;
}

function fromEditorSameSite(s: unknown): CookieDetail["sameSite"] {
  if (s === "no_restriction" || s === "none") return "none";
  if (s === "lax") return "lax";
  if (s === "strict") return "strict";
  return undefined;
}

function toEditorCookie(d: CookieDetail): EditorCookie {
  return {
    name: d.name,
    value: d.value,
    domain: d.hostOnly ? d.domain : `.${d.domain}`,
    path: d.path || "/",
    secure: d.secure,
    httpOnly: d.httpOnly,
    hostOnly: d.hostOnly,
    sameSite: toEditorSameSite(d.sameSite),
    session: d.expires == null,
    ...(d.expires == null ? {} : { expirationDate: d.expires }),
    storeId: null,
  };
}

function fromEditorCookie(c: EditorCookie): CookieDetail {
  const rawDomain = (c.domain ?? "").trim();
  return {
    name: c.name ?? "",
    value: c.value ?? "",
    domain: rawDomain.replace(/^\./, ""),
    path: c.path || "/",
    secure: !!c.secure,
    httpOnly: !!c.httpOnly,
    sameSite: fromEditorSameSite(c.sameSite),
    // Trust an explicit hostOnly; otherwise infer from a missing leading dot.
    hostOnly:
      typeof c.hostOnly === "boolean" ? c.hostOnly : !rawDomain.startsWith("."),
    expires:
      c.session || typeof c.expirationDate !== "number"
        ? undefined
        : Math.floor(c.expirationDate),
  };
}

// --- JSON ---------------------------------------------------------------

function toJson(cookies: CookieDetail[]): string {
  return JSON.stringify(cookies.map(toEditorCookie), null, 4);
}

function fromJson(text: string): CookieDetail[] {
  const data = JSON.parse(text) as unknown;
  const arr = Array.isArray(data)
    ? data
    : Array.isArray((data as { cookies?: unknown })?.cookies)
      ? (data as { cookies: unknown[] }).cookies
      : null;
  if (!arr) throw new Error("expected an array of cookies");
  return (arr as EditorCookie[]).map(fromEditorCookie);
}

// --- Header string ("a=1; b=2") ----------------------------------------

function toHeader(cookies: CookieDetail[]): string {
  return cookies.map((c) => `${c.name}=${c.value}`).join(";");
}

/** Header strings carry no metadata, so every pair is placed on `domain`
 * as a session cookie at path "/". Pairs without an "=" are skipped, matching
 * cookie-editor. */
function fromHeader(text: string, domain: string): CookieDetail[] {
  const out: CookieDetail[] = [];
  for (const raw of text.split(";")) {
    const pair = raw.trim();
    if (!pair) continue;
    const eq = pair.indexOf("=");
    if (eq === -1) continue;
    out.push({
      name: pair.slice(0, eq),
      value: pair.slice(eq + 1),
      domain,
      path: "/",
      secure: false,
      httpOnly: false,
      sameSite: undefined,
      hostOnly: false,
      expires: undefined,
    });
  }
  return out;
}

// --- Netscape / cURL cookies.txt ---------------------------------------

const NETSCAPE_HEADER =
  "# Netscape HTTP Cookie File\n" +
  "# http://curl.haxx.se/rfc/cookie_spec.html\n" +
  "# This file was generated by Spawner";

function toNetscape(cookies: CookieDetail[]): string {
  let out = NETSCAPE_HEADER;
  for (const c of cookies) {
    const domain = c.hostOnly ? c.domain : `.${c.domain}`;
    const prefix = c.httpOnly ? "#HttpOnly_" : "";
    const includeSub = c.hostOnly ? "FALSE" : "TRUE";
    // Session cookies get a 1-day TTL so they survive a round-trip, matching
    // cookie-editor (the format has no "session" flag).
    const expiration =
      c.expires == null
        ? Math.trunc((Date.now() + 86400 * 1000) / 1000)
        : Math.trunc(c.expires);
    out +=
      `\n${prefix}${domain}\t${includeSub}\t${c.path || "/"}\t` +
      `${c.secure ? "TRUE" : "FALSE"}\t${expiration}\t${c.name}\t${c.value}`;
  }
  return out;
}

function fromNetscape(text: string): CookieDetail[] {
  const out: CookieDetail[] = [];
  for (const raw of text.split(/\r?\n/)) {
    let line = raw.trim();
    if (!line) continue;
    let httpOnly = false;
    if (line.startsWith("#HttpOnly_")) {
      httpOnly = true;
      line = line.slice("#HttpOnly_".length);
    } else if (line.startsWith("#")) {
      continue; // comment
    }
    const f = line.split("\t");
    if (f.length < 7) continue;
    const [domain, flag, path, secure, expiration, name, ...rest] = f;
    const exp = Number(expiration);
    out.push({
      name,
      value: rest.join("\t"),
      domain: domain.replace(/^\./, ""),
      path: path || "/",
      secure: secure.toUpperCase() === "TRUE",
      httpOnly,
      sameSite: undefined,
      // Column 2 is the include-subdomains flag: FALSE => host-only.
      hostOnly: flag.toLowerCase() === "false",
      expires: Number.isFinite(exp) && exp > 0 ? Math.floor(exp) : undefined,
    });
  }
  return out;
}

// --- Public API ---------------------------------------------------------

export function serializeCookies(
  cookies: CookieDetail[],
  format: CookieFormat,
): string {
  if (format === "header") return toHeader(cookies);
  if (format === "netscape") return toNetscape(cookies);
  return toJson(cookies);
}

/**
 * Parse cookies in the given format. `domain` is the fallback domain used by
 * the header format (which carries none). Throws on malformed JSON; entries
 * without a name or domain are dropped.
 */
export function parseCookies(
  text: string,
  format: CookieFormat,
  domain = "",
): CookieDetail[] {
  const parsed =
    format === "header"
      ? fromHeader(text, domain)
      : format === "netscape"
        ? fromNetscape(text)
        : fromJson(text);
  return parsed.filter((c) => c.name.trim() !== "" && c.domain.trim() !== "");
}
